services:

  test-app:
    build: ./test-app   # ← ここ変更
    working_dir: /usr/src/app
    volumes:
      - ./test-app:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASS=mypassword
    depends_on:
      - db

  frontend:
    build:
      context: ./denki-app
      dockerfile: Dockerfile.prod
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - NUXT_PUBLIC_API_BASE=https://o-ishisugihara.com/api/denki
    depends_on:
      - test-app
    restart: always

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - test-app
  #     - frontend

volumes:
  db-data:
