FROM node:20 AS build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .
# Nuxt の静的ビルドを生成
RUN npm run build && npm run generate

# ホストへコピーできるように待機コマンド
CMD ["sh", "-c", "cp -r .output/public/* /dist/ && tail -f /dev/null"]
