FROM node:20 AS build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .
ARG API_BASE
ENV API_BASE=$API_BASE
ENV NODE_ENV=production
RUN npm run generate

# 出力は /usr/src/app/dist にできる
