# --- Build Stage ---
FROM node:20 AS build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .
RUN npm run build


# --- Production Stage ---
FROM node:20-alpine AS production

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/.output ./.output

ENV NODE_ENV=production

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
